# Generated by Django 4.1.4 on 2022-12-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='member',
        ),
    ]
