# Generated by Django 4.1.4 on 2022-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
