# Generated by Django 4.1.4 on 2022-12-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_account_question_account2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='account2',
            new_name='account',
        ),
    ]
