# Generated by Django 4.1.4 on 2022-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='MEMO',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
