# Generated by Django 4.1.4 on 2022-12-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_transaction_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='BALANCE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
