# Generated by Django 4.1.4 on 2022-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_transaction_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=20)),
            ],
        ),
    ]
