# Generated by Django 4.1.4 on 2022-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productpoint',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
