# Generated by Django 4.1.4 on 2023-01-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_productimage1_product_productimage2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productimage2',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='AMOUNT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='MEMO',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
