# Generated by Django 4.1.4 on 2023-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_qrcode_transaction_proname_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productlimit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
