# Generated by Django 4.1.4 on 2023-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_productlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='rankinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankname', models.CharField(max_length=20)),
                ('rankimg', models.CharField(max_length=20)),
            ],
        ),
    ]
