# Generated by Django 4.1.4 on 2023-01-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinfo',
            name='rankpoint',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
