# Generated by Django 4.1.4 on 2023-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_member_nname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinfo',
            name='rankengname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
