# Generated by Django 4.1.4 on 2023-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rankinfo_rankengname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productkind',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
