# Generated by Django 4.1.4 on 2023-01-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
