# Generated by Django 4.1.4 on 2023-01-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_member_email_remove_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
