# Generated by Django 4.1.4 on 2023-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_member_nname_remove_member_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='AC_CODE',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=43, primary_key=True, serialize=False),
        ),
    ]
