# Generated by Django 4.1.4 on 2023-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_aiwash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiwash',
            name='MEM',
            field=models.CharField(max_length=36),
        ),
    ]
