# Generated by Django 4.1.4 on 2023-01-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_aiwash_mem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aiwash',
            table='AIwash',
        ),
    ]
