# Generated by Django 4.1.4 on 2023-01-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_aiwash_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwash',
            name='APPID',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwash',
            name='CDATE',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwash',
            name='ORDID',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwash',
            name='TAX',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwash',
            name='TOTALMONEY',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiwash',
            name='MEM',
            field=models.CharField(max_length=43),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
