# Generated by Django 4.1.4 on 2023-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_aiwash_appid_aiwash_cdate_aiwash_ordid_aiwash_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CDATE',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TIME',
            field=models.IntegerField(null=True),
        ),
    ]
