# Generated by Django 4.1.4 on 2023-01-11 15:08

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_transaction_cdate_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiwash',
            name='MEM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='FKcheck',
            field=models.CharField(default=myapp.models.UUIDrand, max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='Raccesscode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='Rstate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TIME',
            field=models.IntegerField(),
        ),
    ]
