# Generated by Django 4.1.4 on 2023-01-11 16:07

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_aiwash_mem_alter_login_fkcheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='FKcheck',
            field=models.CharField(default=myapp.models.UUIDrand, max_length=36),
        ),
        migrations.AlterField(
            model_name='login',
            name='Raccesscode',
            field=models.CharField(max_length=43),
        ),
        migrations.AlterField(
            model_name='login',
            name='Rstate',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='MEMID',
            field=models.CharField(max_length=43),
        ),
    ]
