# Generated by Django 4.1.4 on 2023-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_login_fkcheck_alter_login_raccesscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=43),
        ),
    ]
