# Generated by Django 4.1.4 on 2023-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_member_id_alter_member_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=43),
        ),
    ]
