# Generated by Django 4.1.4 on 2023-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_member_id_alter_member_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiwash',
            name='TAX',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='CDATE',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TIME',
            field=models.IntegerField(null=True),
        ),
    ]
