# Generated by Django 4.1.4 on 2023-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
