# Generated by Django 4.1.4 on 2023-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_qrcode_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
