# Generated by Django 4.1.4 on 2023-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_delete_qrcode_transaction_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORD', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('time_elapsed', models.IntegerField(null=True)),
                ('overtime', models.IntegerField(null=True)),
            ],
        ),
    ]
